package model;

/**
 * Represents an administrator user in the system, extending the base Profile class. This class contains administrator-specific attributes and functionality, including access to administrative accounts and privileged operations.
 *
 * Administrators have additional security features and access rights compared to regular users, allowing them to manage system-wide operations and user accounts.
 */
public class Admin extends Profile
{

    private String a_current_account;

    /**
     * Constructs a new Admin instance with full profile information including ID. This constructor is typically used when loading existing administrator data from the database where the profile ID is already assigned.
     *
     * @param p_id the unique identifier for the administrator profile
     * @param p_email the email address associated with the administrator account
     * @param p_username the username used for administrator authentication
     * @param p_password the password used for administrator authentication
     * @param p_name the first name of the administrator
     * @param p_lastname the last name of the administrator
     * @param p_telephone the telephone number of the administrator
     * @param a_current_account the current administrative account number or identifier
     */
    public Admin(int p_id, String p_email, String p_username, String p_password, String p_name, String p_lastname, String p_telephone, String a_current_account)
    {
        super(p_id, p_email, p_username, p_password, p_name, p_lastname, p_telephone);
        this.a_current_account = a_current_account;
    }

    /**
     * Constructs a new Admin instance with basic profile information excluding ID. This constructor is typically used when creating new administrator accounts where the profile ID will be generated by the database system.
     *
     * @param p_email the email address associated with the administrator account
     * @param p_username the username used for administrator authentication
     * @param p_password the password used for administrator authentication
     * @param p_name the first name of the administrator
     * @param p_lastname the last name of the administrator
     * @param p_telephone the telephone number of the administrator
     * @param a_current_account the current administrative account number or identifier
     */
    public Admin(String p_email, String p_username, String p_password, String p_name, String p_lastname, String p_telephone, String a_current_account)
    {
        super(p_email, p_username, p_password, p_name, p_lastname, p_telephone);
        this.a_current_account = a_current_account;
    }

    /**
     * Retrieves the current administrative account identifier. This method returns the account number or identifier associated with the administrator's privileged access rights.
     *
     * @return the current administrative account number or identifier
     */
    public String getCurrent_account()
    {
        return a_current_account;
    }

    /**
     * Sets the current administrative account identifier. This method updates the account number or identifier associated with the administrator's privileged access rights.
     *
     * @param a_current_account the new administrative account number or identifier to set
     */
    public void setCurrent_account(String a_current_account)
    {
        this.a_current_account = a_current_account;
    }

    /**
     * Returns a string representation of the administrator profile. This method provides a formatted string containing all profile information along with a masked version of the administrative account for security purposes.
     *
     * @return a formatted string representation of the administrator profile with sensitive account information partially masked
     */
    @Override
    public String show()
    {
        return "Admin {" + super.toString() + (a_current_account != null ? ", Current account: **** **** **** " + a_current_account.substring(12, 16) : null) + "}";
    }
}
