package model;

/**
 * Represents a regular user in the system, extending the base Profile class. This class contains user-specific attributes including gender information and payment card details, providing the complete data model for standard user accounts in the application.
 *
 * User objects are used throughout the system for authentication, profile management, and personalization features.
 */
public class User extends Profile
{

    private Gender u_gender;
    private String u_card;

    /**
     * Constructs a new User instance with full profile information including ID. This constructor is typically used when loading existing user data from the database where the profile ID is already assigned.
     *
     * @param u_id the unique identifier for the user profile
     * @param p_email the email address associated with the user account
     * @param p_username the username used for user authentication
     * @param p_password the password used for user authentication
     * @param p_name the first name of the user
     * @param p_lastname the last name of the user
     * @param p_telephone the telephone number of the user
     * @param u_gender the gender identity of the user
     * @param u_card the payment card number associated with the user account
     */
    public User(int u_id, String p_email, String p_username, String p_password, String p_name, String p_lastname, String p_telephone, Gender u_gender, String u_card)
    {
        super(u_id, p_email, p_username, p_password, p_name, p_lastname, p_telephone);
        this.u_gender = u_gender;
        this.u_card = u_card;
    }

    /**
     * Constructs a new User instance with basic profile information excluding ID. This constructor is typically used when creating new user accounts where the profile ID will be generated by the database system.
     *
     * @param p_email the email address associated with the user account
     * @param p_username the username used for user authentication
     * @param p_password the password used for user authentication
     * @param p_name the first name of the user
     * @param p_lastname the last name of the user
     * @param p_telephone the telephone number of the user
     * @param u_gender the gender identity of the user
     * @param u_card the payment card number associated with the user account
     */
    public User(String p_email, String p_username, String p_password, String p_name, String p_lastname, String p_telephone, Gender u_gender, String u_card)
    {
        super(p_email, p_username, p_password, p_name, p_lastname, p_telephone);
        this.u_gender = u_gender;
        this.u_card = u_card;
    }

    /**
     * Retrieves the gender identity of the user.
     *
     * @return the Gender enum value representing the user's gender identity
     */
    public Gender getGender()
    {
        return u_gender;
    }

    /**
     * Sets the gender identity for the user.
     *
     * @param u_gender the new Gender enum value to assign to the user
     */
    public void setGender(Gender u_gender)
    {
        this.u_gender = u_gender;
    }

    /**
     * Retrieves the payment card number associated with the user account.
     *
     * @return the complete payment card number as a string
     */
    public String getCard()
    {
        return u_card;
    }

    /**
     * Sets the payment card number for the user account.
     *
     * @param u_card the new payment card number to associate with the user
     */
    public void setCard(String u_card)
    {
        this.u_card = u_card;
    }

    /**
     * Returns a simplified string representation of the user. This method overrides the parent class toString() to provide only the username, which is useful for display purposes in UI components like combo boxes and lists.
     *
     * @return the username of the user as the string representation
     */
    @Override
    public String toString()
    {
        return super.getUsername();
    }

    /**
     * Returns a detailed string representation of the user profile. This method provides a formatted string containing all profile information along with a masked version of the payment card for security purposes.
     *
     * @return a formatted string representation of the user profile with sensitive card information partially masked
     */
    @Override
    public String show()
    {
        return "User {" + super.toString() + ", Gender: " + u_gender + (u_card != null ? ", Card: **** **** **** " + u_card.substring(12, 16) : "") + "}";
    }
}
